### PR TITLE
Added den for nf_elt and conversin to/ from fmpz_mat row

### PR DESCRIPTION
**Pull request by fieker**
may need some revision as to names, ordering of arguments and such...
removes a fair amount of overhead in Nemo

### CODE REVIEW

**Comment by wbhart** [comment]
I think the get_den function can go in the inlines.c file. The reason is that all the Antic C code will have to distinguish the three cases linear/quadratic/general, and so the function isn't useful in Antic C code itself.

But it is useful from the Julia part of Antic. That means it satisfies the general requirement to go in inlines.c, I think. This also saves documenting and testing it, since that is not required for inlines. :-)

As for the get_mat_row etc. the return of a denominator separately seems redundant.

I would prefer:

void nf_elem_num_get_mat_row(fmpz_mat_t M, const int i, const nf_elem_t b, const nf_t nf)

which sets row i of matrix M to the numerator of b. If the denominator is required, then the get_den function can be called separately.

This function and its pair shouldn't be inlines, as they have general usefulness. They should be ordinary functions in the library and documented and tested.

Bill.

**Comment by fieker** [comment]
On Wed, May 06, 2015 at 02:01:04PM -0700, wbhart wrote:

> I think the get_den function can go in the inlines.c file. The reason is that all the Antic C code will have to distinguish the three cases linear/quadratic/general, and so the function isn't useful in Antic C code itself.
> 
> But it is useful from the Julia part of Antic. That means it satisfies the general requirement to go in inlines.c, I think. This also saves documenting and testing it, since that is not required for inlines. :-)
> 
> As for the get_mat_row etc. the return of a denominator separately seems redundant.
> 
> I would prefer:
> 
> void nf_elem_num_get_mat_row(fmpz_mat_t M, const int i, const nf_elem_t b, const nf_t nf)
> 
> Almost - I left it at to_mat_row, but the signature is what you suggest
> which sets row i of matrix M to the numerator of b. If the denominator is required, then the get_den function can be called separately.
> 
> done.
> This function and its pair shouldn't be inlines, as they have general usefulness. They should be ordinary functions in the library and documented and tested.
> They are documented, but not tested. I haven't tried to understand the
> testing system yet. However, Julia says they are working...

Greetings
  Claus

PS.: do you want a pull request?

**Comment by wbhart** [comment]
This already is a pull request.

Testing is easy. Just cut'n'paste one of the other Antic test files. For
example, nf_elem/test/t-add_sub.c already generates random number fields of
various degrees.

In this case, generating random matrices and nf_elems for various degree
random fields, and putting the nf_elem into the matrix with one of the
functions and getting it back out with the other and comparing equality
should do as a test.

To generate random matrices of a given size, one can use fmpz_mat_randbits,
for example.

To add a test file, you just add a .c file whose name begins "t-" to the
nf_elem/test directory. Flint will automatically pick it up and build it
and run it when you do:

make check MOD=nf_elem

Bill.

**Comment by wbhart** [comment]
Something seems to have gone wrong with this pull request, as it has accumulated unrelated commits. 

I have merged the original pull request, which was for get/set_den and from/to_mat_row. However, I made a large number of changes for consistency.
- I have renamed from/to_mat_row to get/set_fmpz_mat_row in line with the flint naming conventions (there's not much point having two different sets of naming conventions to learn). Also, we may later want to write a similar function for fmpq_mat.
- The set_fmpz_mat_row function now sets the denominator to 1. I'm not sure if this was intended or not. I've changed the docs to reflect this. If you really wanted one which didn't set the denominator (remember, the denominator of a freshly initialised nf_elem_t is 0, not 1), then we should rename it to nf_elem_num_set_fmpz_mat_row.

It seems to me that what was originally intended was a function which stores not just the numerator but also the denominator in the matrix. However, if I recall, our fmpq_mat module stores a denominator for every entry. So there basically isn't a suitable flint matrix type for this sort of thing.

I originally objected to these functions taking a denominator on the grounds that the fmpz_mat_t doesn't store one. But I'm thinking of changing that back. It makes sense if the set_fmpz_mat_row function sets the nf_elem_t when given an fmpz_mat_t row and a denominator. And it makes sense if the get_fmpz_mat_row function sets a row of the fmpz_mat_t and sets an fmpz_t to the denominator.

Sorry if that's what you had originally, but I now think that's the right way to do it. I was thinking in terms of the matrix row, rather than in terms of the nf_elem_t.

I'll change this in a later commit I think.
- int -> slong throughout for poly degrees and matrix dimensions (int is too small and not the type used throughout flint)
- spaces before and after +, -, >=, <=, =, etc. in code
- at least 3 spaces indent (4 is also ok)
- added test code for both get/set_den and get/set_fmpz_mat_row
- fmpz \* should not be used instead of fmpz_t. The former is only when you intend a low level array of integers. I've changed this in the prototype of the functions.
- I moved get_set_den from inlines back into nf_elem.h. Basically I changed my mind about these functions. I think they are generally useful to a library user not just for Nemo.
- Made a note that set_den assumes denominator is positive.

**Comment by wbhart** [comment]
I've now changed get/set_fmpz_mat_row to take/return a denominator. I think this was the originally intended interface, and I now see why it makes sense.

**Pull request closed without merging**
