### PR TITLE
version_script support

### PR DESCRIPTION
**Pull request by jgmbenoit**
Description: upstream: version script support
 Provides a version script [1] for the shipped library. It was
 basically extracted by hand from the package C headers themselves
 with the help of the following sed script:
 .
 ##antic2map.sed
 /^static __inline__/,/^}/d
 s@FLINT_DLL[ ]*@@g
 s@^\(void\|int\|ulong\|slong\|long int\|double\|char\)[* ]*\([a-zA-Z0-9_]*\)(.*$@\2;@p
 # eos
 .
 [1] https://www.gnu.org/software/gnulib/manual/html_node/LD-Version-Scripts.html
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2022-02-13

### CODE REVIEW

**Comment by wbhart** [comment]
It looks like this breaks the Clang/MacOS build.

**Comment by jgmbenoit** [comment]
I am not familiar with clang. I guessed clang and gcc shared the same option. I guess the a case/esac can be introduce in the c`configure` script as workaround.

**Comment by jgmbenoit** [comment]
I have just hardened the patch. Now it works around Darwin. This workaround can be easily updated for other OS missing `--version-script` support.

**Comment by wbhart** [comment]
I see a red X in the CI. There's a missing file and then a pile of Python backtrace.

**Pull request closed without merging**
