### PR TITLE
Introduce nf_init_randtest to simplify testing

### PR DESCRIPTION
**Pull request by saraedum**
also fixes a problem in multiplication with the generator when the defining polynomial is linear but not monic.

`nf_init_randtest` has been implemented originally by @videlec as part of e-antic.

### CODE REVIEW

**Comment by saraedum** [comment]
@videlec: Your test in https://github.com/videlec/e-antic/blob/master/nf_elem/test/t-mul_gen.c#L48 explicitly excluded linear defining polynomials. Is there any reason why they should be excluded? Or was this just added to make tests since e-antic does not really care that much about linear polynomials anyway.

**Comment by videlec** [comment]
> @videlec: Your test in https://github.com/videlec/e-antic/blob/master/nf_elem/test/t-mul_gen.c#L48 explicitly excluded linear defining polynomials. Is there any reason why they should be excluded? Or was this just added to make tests since e-antic does not really care that much about linear polynomials anyway.

Sorry, I don't remember why I did that.

**Comment by wbhart** [comment]
This code looks ok. Do you want me to merge it now or do you still want to make changes to it?

**Comment by saraedum** [comment]
@wbhart I believe this code can be merged.

**Pull request merged**
