### PR TITLE
Fix headers

### PR DESCRIPTION
**Pull request by thofma**
Also removes the license text for GPL.

### CODE REVIEW

**Comment by wbhart** [comment]
Can you put the GPL back in though. It is required to be in there. The LGPL is only an extension to the GPL and it isn't valid on its own.

**Comment by wbhart** [comment]
By the way, the actual LGPL file seems to have some unneeded extra lines of text at the end.

**Comment by wbhart** [comment]
Oh wait, that extra stuff is apparently supposed to be in there. Bizarre.

**Comment by thofma** [comment]
Restored the gpl text. Regarding LGPL, I just took whatever bizarre things you put into flint.

**Comment by wbhart** [comment]
Yeah we are doing it wrong in both projects. Apparently the GPL is supposed to go in COPYING and the LGPL in COPYING.LESSER.

https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by wbhart** [comment]
GitHub uses it for detection of license etc.

**Comment by wbhart** [comment]
But in Flint I am just going to put the gpl2 text file in and be done with it. Licenses are annoying.

**Comment by thofma** [comment]
Do you want me to change something here?

**Comment by wbhart** [comment]
Nah it's fine.

**Pull request merged**
