### PR TITLE
NUCOMP and NUDUPL optimization

### PR DESCRIPTION
**Pull request by rostislav**
Hello Mr. Hart,

Here are the promised improvements to the algorithms for composition of quadratic forms.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks for these contributions. I have one question though. The replacement of gcdinv with gcdext should in theory be a slowdown as the latter has to compute both cofactors.

Have you timed this on reasonable sized examples to check that it isn't slowing the code down? As nudupl is called often, I would hate to not check this before merging.

**Comment by rostislav** [comment]
I was using NUDUPL only for forms where D is prime, so a and b cannot have common factors. In this case `fmpz_invmod` completes successfully and we don't call `fmpz_xgcd`.

However, if D is not prime, there may be common factors in a and b, and the more expensive `fmpz_xgcd` would be used, which is indeed undesirable. I will soon submit a different solution that should work efficiently for all D.

**Comment by rostislav** [comment]
Please see the new version which doesn't use `fmpz_xgcd`.

**Comment by wbhart** [comment]
Yeah, that looks great. Thanks for the contribution!

**Pull request merged**
