### PR TITLE
Absolute norm with divisor.

### PR DESCRIPTION
**Pull request by fieker**
however, It seems to be all or nothing.

### CODE REVIEW

**Comment by thofma** [comment]
I have cleaned it up. If you want I can squash it.

As soon as we have the resultant stuff in flint2 we can write a proper test for the norm_div function here.

**Comment by wbhart** [comment]
Thanks Tommy.

I think Claus' idea of introducing an interface in Flint for a modular
resultant with a supplied bound and having the existing Flint function call
it instead would be quite useful.

We should look into this. Though I don't see how such a function benefits
from knowing a divisor. Is it rather a multiple of the resultant that it
knows (which can act as a bound)?

**Comment by thofma** [comment]
I'm almost there with merging Claus' flint patch.

The function is useful if you know a (large) divisor D of the resultant and a bound B on the resultant. Then in the modular approach you only need primes to "cover" the B/D part. If I remember correctly this is the idea.

**Comment by wbhart** [comment]
Ah, I see. Well it'll come down to whether we can implement something
general like that which doesn't cause a performance regression, when say D
= 1.

**Comment by thofma** [comment]
I fixed the (trivial) linear case, indentation and added test. Should be mergable (hopefully).

**Comment by wbhart** [comment]
Looks good to me. There are only two changes I would suggest. 

The first is to the documentation. Would you be happy with the wording:
-    Set \code{res} to the absolute norm of the given number
-    field element $a$, divided by \code{div} . Assumes the result to be an integer and having
-    at most \code{nbits} bits.
  +

The second change is that all high level functions are supposed to allow arbitrary aliasing. So it is better to make a copy of div if div == res and then remove the comment about it not being allowed in the documentation.

Quite a few other functions have code to handle aliasing, so there are some example you can follow there.

Otherwise everything else looks ok to me.

**Comment by wbhart** [comment]
And of course _nf_elem_norm_div should be documented too. It of course does not necessarily need to handle aliasing since it is lower level.

**Comment by thofma** [comment]
I am happy with any rewording (I did not wrote it).

Concerning the aliasing and the note in the documentation. I tried to imitate the documentation of fmpq_mat_scalar_mul_fmpz. Here it is actually not aliasing, since div and res have different types and div == res is not possible. I just wanted to note that fmpq_numref(res) == div and/or fmpq_denref(res) == div is not allowed (at the moment). Should I allow this? Does every top-level flint function allow this, e.g. fmpq_mul_fmpz? Glancing over it, I would say no.

**Comment by wbhart** [comment]
It seems I misunderstood the comment about aliasing. I would say that we don't do anything to handle aliasing between different types. No need to actually mention this in the documentation. You would have to go quite out of your way to put an existing fmpz into an fmpq without using fmpz_set (which would be fine). So usually there is no need to document that this is not supported.

So I will just merge this and change the documentation.

**Comment by wbhart** [comment]
Oh except I still need documentation for _nf_elem_norm_div. How does it differ from nf_elem_norm_div?

**Comment by thofma** [comment]
Thanks. I remembered that fmpq_mat_scalar_mul_fmpz had such a comment. I thought I should add that too. But you are right. Here it does more harm than good and sounds confusing.

Edit: The _ version returns the result individually as numerator and denominator (fmpzs).

**Comment by wbhart** [comment]
Yeah fmpq_mat_scalar_mul_fmpz probably shouldn't have such a comment. There's only so much we can be responsible for.

**Comment by thofma** [comment]
Do you want me to add the documentation for the _ version?

**Comment by wbhart** [comment]
Yes please, or just email it to me so I can add it.

**Pull request merged**
