### PR TITLE
Add a sign parameter for the mod fmpz operation

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by wbhart** [comment]
Are we sure we want to go this way? At least in Flint, smod is used for the symmetric mod system. Also, you are changing the behaviour of user facing functions. This is likely to break people's code. Antic is extensively used by external projects. At the very least you should ask on the Flint list if these changes are ok.

**Comment by thofma** [comment]
I added these functions 3 months ago and there has not been a release since then. I doubt this is breaking peoples code.

In flint there is smod (_fmpz_vec_scalar_smod_fmpz), mods (fmpz_mods) and also the sign argument (fmpz_CRT_ui).

I am happy to add new functions. Do you prefer smod or mods?

**Comment by wbhart** [comment]
I prefer smod. This is the original convention which goes back to Flint1 and is certainly present in 2011. However mods is from a student from a few years ago. I'll open a ticket to fix that.

**Comment by wbhart** [comment]
I agree that the CRT has a sign parameter. That seems to be the convention when doing lifting. I'm not so worried about changing it though. It's not performing a reduction mod p per se.

**Comment by thofma** [comment]
OK, I will add some `smod` functions.

**Comment by thofma** [comment]
I updated the PR.

**Comment by wbhart** [comment]
The prototype for the smod version in the docs is not quite correct.

**Comment by thofma** [comment]
Oops, fixed the docs.

**Pull request merged**
